apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tlstest.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    server {
        listen 80;
        server_name {{ .Values.tls.certCN }};
    
        # Redirect HTTP to HTTPS
        #return 301 https://{{ .Values.tls.certCN }}$request_uri;

        root /usr/share/nginx/html;
        location / {
            index index.html index.htm;
            autoindex off;
            try_files $uri $uri/ =404;
        }


    }
    
    server {
        listen 443 ssl;
        server_name {{ .Values.tls.certCN }};

        root /usr/share/nginx/html;
        location / {
            index index.html index.htm;
            autoindex off;
            try_files $uri $uri/ =404;
        }
    
        # TLS settings
        ssl_certificate     /etc/nginx/tls/tls.crt;
        ssl_certificate_key /etc/nginx/tls/tls.key;
    
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;
    }
