apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tlstest.fullname" . }}
  namespace: "{{ .Release.Namespace }}"    
  labels:
    app: tlstest-nginx
    tlstest.koppzu.de/certCN: {{ .Values.tls.certCN | default "localhost" | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tlstest-nginx
  template:
    metadata:
      labels:
        app: tlstest-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:{{ .Values.nginx.image.tag }}
          imagePullPolicy: IfNotPresent
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - "update-ca-certificates"
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: nginx-certs-volume
              mountPath: "/etc/nginx/tls"
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
              readOnly: true
            - name: ca-certs-volume
              mountPath: "/usr/local/share/ca-certificates/"
              readOnly: true
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
      volumes:
        - name: nginx-certs-volume
          secret:
            secretName: {{ include "tlstest.fullname" . }}-certs
        - name: ca-certs-volume
          secret:
            secretName: {{ include "tlstest.fullname" . }}-cacerts
        - name: nginx-config
          configMap:
            name: {{ include "tlstest.fullname" . }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
