---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tlstest.fullname" . }}-certs
  namespace: "{{ .Release.Namespace }}"
  type: Opaque
data:
  tls.crt: {{ .Values.tls.cert | b64enc | quote }}
  tls.key: {{ .Values.tls.key | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tlstest.fullname" . }}-cacerts
  namespace: "{{ .Release.Namespace }}"
  type: Opaque
data:
  tls.cacert.crt: {{ .Values.tls.cacert | b64enc | quote }}
