apiVersion: v1
kind: Service
metadata:
  name: {{ include "tlstest.fullname" . }}
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: tlstest-nginx
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
    - name: http
      port: 80
      targetPort: http
      protocol: TCP

  selector:
    app: tlstest-nginx
